### PR TITLE
Fixing the Footnotes and Feature Flag on the Function Contracts RFC

### PR DESCRIPTION
**Pull request by JustusAdam**
### Description of changes: 

The [function contracts RFC](https://model-checking.github.io/kani/rfc/rfcs/0009-function-contracts.html) as rendered on the website has broken footnotes. The reason is that mdbooks renders markdown differently than GitHub (of course, why would the same syntax, for the same language exhibit the same behavior with two different compilers, that'd just be silly.). Instead of rendering all footnotes at the bottom they were interspersed with the text, breaking the reading flow. In addition the footnotes of mdbook do not support multiple paragraphs and code blocks so one of the footnotes required rephrasing.

Also fixes the incorrectly named `-Zcontracts` feature flag

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by jaisnan** [comment]
Can you link or add the screenshot for the rendered page after the change?

**Review by jaisnan — APPROVED** [review]
Approving! If possible, could you add a link to rendered page after the change?

**Comment by JustusAdam** [comment]
> Approving! If possible, could you add a link to rendered page after the change?

Is this what you were thinking of?

Screenshot 2023-09-11 at 5 02 18 PM

**Comment by jaisnan** [comment]
> > Approving! If possible, could you add a link to rendered page after the change?
> 
> Is this what you were thinking of?
> 
> Screenshot 2023-09-11 at 5 02 18 PM

Yes, thank you! Looks great!

**Review by feliperodri — APPROVED** [review]

**Pull request merged**
