### PR TITLE
Add tests for `forget`

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Adds a positive and a negative test case for `forget` and updates the support table accordingly.

### Resolved issues:

Part of #727 

### Call-outs:

PR was originally "Disable `forget` intrinsic" but was changed after discussion below. Description included below for reference.

> Removes the implementation for `forget`, which was being encoded as a no-op.
> 
> Note that this is not the well-known `forget` which calls `ManuallyDrop`, but an alternative that moves the value out of scope without calling drop functions (used by `mem::forget_unsized`): https://doc.rust-lang.org/std/intrinsics/fn.forget.html

### Testing:

* How is this change tested? Existing regression.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
It seems to me that using a no-op for `forget` is sound since the only effect of using the `forget` intrinsic is to produce a compiler error if the value is referenced after "forgetting" it. I cannot think of any other verification-related effects of calling it.

**Comment by adpaco-aws** [comment]
Thanks @zhassan-aws for the detailed explanation!

To be clear, I was under the impression this was not sound because I thought we had to generate code for "forgetting" the value in CBMC. But as you explained we do not need to do anything during code generation, so a no-op would be fine.

Now, instead of removing it, I was thinking of adding two tests similar to the example found [here](https://doc.rust-lang.org/std/mem/fn.forget.html#relationship-with-manuallydrop) but using this `forget`.
```rust
fn main() {
let mut v = vec![65, 122];
let s = unsafe { String::from_raw_parts(v.as_mut_ptr(), v.len(), v.capacity()) };
std::intrinsics::forget(v);
assert!(v[0] == 65); // this causes failure to codegen
assert_eq!(s, "Az");
}
```
This should fail to codegen, and another test not including the first assertion should pass. What do you think?

**Comment by adpaco-aws** [comment]
Just pushed the changes I was proposing because I figured it's something we would like to have anyway. Updated title and description as well.

**Review by zhassan-aws — APPROVED** [review]
Makes sense to me (technically it would be a compilation error as opposed to a codegen failure with the first assert, but I guess for the purpose of compiletest, it's the same thing).

**Comment by adpaco-aws** [comment]
Right, switched to `kani-check-fail` which is used to indicate errors before codegen.

**Pull request merged**
