### PR TITLE
Hooked up __CProver_cover

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

Hook up CBMC's `CProverCover` builtin-in function. Enabling it currently requires running CBMC with the `--cover cover` option, but nevertheless it may be helpful for implementing #696.

### Resolved issues:

Partially addresses #696 

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by tedinski** [comment]
`--visualize` for instance turns on `--cover location`. Can we have `--cover cover` at the same time? Do they conflict?

**Comment by zhassan-aws** [comment]
> `--visualize` for instance turns on `--cover location`. Can we have `--cover cover` at the same time? Do they conflict?

Unfortunately, `--cover cover` conflicts with other options that we use:
```
$ cbmc --cover cover --unwinding-assertions cover.c 
--cover and --unwinding-assertions must not be given together
```

**Comment by tedinski** [comment]
> Unfortunately, `--cover cover` conflicts with other options that we use:

Already an issue: https://github.com/diffblue/cbmc/issues/6561

**Comment by celinval** [comment]
I was chatting with @zhassan-aws about this. The `--cover cover` option turns off the properties verification and it conflicts with `--cover assertions`. So that would force us to run cbmc twice. @zhassan-aws was going to chat with @tautschnig to see if it's possible to enable both and when could this be done.

Another odd thing is that if the `--cover cover` is not enabled, CBMC prints the following warning:
```
WARNING: no body for function __CPROVER_cover
```

**Review by celinval — APPROVED** [review]
Despite the limitations we've found so far which blocks us from taking advantage of CProver cover, this PR only adds the cover to the `cbmc` crate.

**Pull request merged**
