### PR TITLE
Fix issues and Update toolchain 10-26

### PR DESCRIPTION
**Pull request by jaisnan**
Resolves issues caused by
1. https://github.com/rust-lang/rust/pull/116958
2. https://github.com/rust-lang/rust/pull/117103 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]
Looks good! Thanks Jai

**Comment by adpaco-aws** [comment]
Despite this looking like a simple renaming, there is a performance regression in the `hashset/check_insert_two_concrete` benchmark. Comparing runs with the latest run in `main`:

| | This PR | Latest in `main` | Difference |
| --- | --- | --- | --- |
| number_program_steps |  33199 | 28927 | **+4272** |
| number_vccs | 3310 | 2859 | **+451** |
| solver_runtime | 48.81328 | 12.15361 | **+301.636%** |
| symex_runtime | 31.2295 | 28.7472 | +8.635% |
| verification_time |  88.96327 | 48.72418 | **+82.585%** |

@zhassan-aws @tautschnig have you seen this benchmark fail lately? Do you have any suggestions?

**Comment by jaisnan** [comment]
@adpaco-aws, the second issue https://github.com/rust-lang/rust/pull/117103 required very minor refactoring, which is contained in this commit https://github.com/model-checking/kani/pull/2843/commits/dce6524b61967929394f16d94a74da28d43e1321. It's possible that this could be causing the performance regression.

**Comment by celinval** [comment]
Hi @jaisnan, can you compare the MIR emitted before and after the toolchain upgrade ([Instruction here](https://model-checking.github.io/kani/cheat-sheets.html#debug))?

My guess is that the performance impact doesn't have anything to do with the conflict resolutions but more with an underlying change to the compiler.

**Comment by adpaco-aws** [comment]
We agreed to merge the PR and continue the investigation in a separate issue. @jaisnan do you mind opening that?

**Pull request merged**
