### PR TITLE
Update Rust toolchain to nightly-2023-02-03

### LINKED ISSUE #2114: Update rust toolchain version for Kani 0.21
Biweekly update for the rust toolchain version. For Kani 0.21, we will target the version: nightly-2023-01-30.

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

This PR is blocked on waiting for https://github.com/model-checking/kani/pull/2149 to be merged first.
Once that's merged, this PR should be rebased and force pushed.

The following upstream changes had impact this week:

* (`Primitive::Pointer`) https://github.com/rust-lang/rust/pull/107248
* (`ParamEnv`) https://github.com/rust-lang/rust/pull/105582
* (`local_def_id`) https://github.com/rust-lang/rust/pull/107206
* (`GeneratorWitnessMIR`) https://github.com/rust-lang/rust/pull/101692
* (`ConstEvalCounter`) https://github.com/rust-lang/rust/pull/106227

This change caused all stubbing code to fail (CI will fail) and I could use help with it:

* https://github.com/rust-lang/rust/pull/106812

I **think** what we're seeing is that `queries.global_ctxt()?` is now "held" by rustc_driver across the `after_expansion` call, and consequently our use of `queries.global_ctxt().unwrap().enter()` fails here:

https://github.com/model-checking/kani/blob/417895883e9f69a376d230cea16926a6d6511040/kani-compiler/src/kani_middle/stubbing/annotations.rs#L43

This might be a bug with that change in upstream rust? @celinval what do you think?

### Resolved issues:

Resolves #2114

### Testing:

* How is this change tested? ci

* Is this a refactor change? no

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by celinval** [comment]
Yeah, it could've been a mistake on their side. @oli-obk was this restriction done on purpose?

 We could work around it by moving the stubbing code to the `after_analysis` callback. My guess is that `after_parsing` might be too soon, since we deal with path resolution and the macro might've not been expanded yet.

**Comment by oli-obk** [comment]
Ah no, that's a bug on our end. I think we could just pass the TyCtxt into the after_analysis query, but short term we should just stop holding the lock on the rustc side

**Comment by celinval** [comment]
> Ah no, that's a bug on our end. I think we could just pass the TyCtxt into the after_analysis query, but short term we should just stop holding the lock on the rustc side

@oli-obk do you think you can own the fix, or do you want us to submit a patch upstream?

**Comment by oli-obk** [comment]
I'll handle it, should be fixed in the next few days

**Comment by oli-obk** [comment]
The upstream patch has landed, but I think it didn't make today's nightly build, so you'll need to wait another day

**Comment by celinval** [comment]
Perfect! Thanks a lot @oli-obk.

**Comment by qinheping** [comment]
closed as #2291 created.

**Pull request closed without merging**
