### PR TITLE
Add M1 to the list of supported targets

### LINKED ISSUE #1167: Kani won't install on Apple M1
I've installed kani on Apple M1 running MacOS 11.6.5 with

```
git clone https://github.com/model-checking/kani.git kani
cd kani && git submodule update --init
PATH=$HOME/.cargo/bin:$PATH && cd kani && \
	    ./scripts/setup/macos-10.15/install_deps.sh && \
	    ./scripts/setup/install_rustup.sh && \
	    cargo build --workspace
export PATH=$HOME/.cargo/bin:$(pwd)/kani/scripts:$PATH
```

(Actually, I modified install_deps.h to brew install universal-ctags instead of ctags.)

Now I run kani on a regression test with

```
pushd kani/tests/kani/FunctionCall_NoRet-NoParam/
kani main.rs
```

and I get an exception and stack trace with

```
error: Kani requires the target platform to be `x86_64-unknown-linux-gnu` or `x86_64-apple-darwin`, but it is arm64-apple-macosx11.0.0
error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

In preparation for adding M1 bundles to the releases, add M1 (`aarch64-apple-darwin`) to the list of supported targets.

### Resolved issues:

Resolves #1167 

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]
@tedinski Any thoughts on how we can test these changes?

**Comment by tedinski** [comment]
There's a step in the release process meant to ensure everything actually works as intended. It's the post-github-release, pre-crates.io-release validation step. (That's currently broken when using --git, so we have to do that bundle thing instead.)

**Comment by celinval** [comment]
> There's a step in the release process meant to ensure everything actually works as intended. It's the post-github-release, pre-crates.io-release validation step. (That's currently broken when using --git, so we have to do that bundle thing instead.)

Do we do that for all architectures though?

**Comment by zhassan-aws** [comment]
> Do we do that for all architectures though?

AFAIK, no.

**Pull request merged**
