### PR TITLE
add VSTTE 2024 paper files

### PR DESCRIPTION
**Pull request by rahulku**
Add files for the VSTTE2024 invited short paper.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by carolynzech** [comment]
Did you mean to update the `s2nquic` tests? Your commit updates those files as well.

**Comment by tautschnig** [comment]
I believe [success.png](https://github.com/model-checking/kani/pull/3472/files#diff-095d66d7f46fcaea181c21a9afefe2a3f05b06e83425daf0dfe6a7b0e328e132) is no longer needed.

**Comment by rahulku** [comment]
fixed.

**Comment by rahulku** [comment]
> Did you mean to update the `s2nquic` tests? Your commit updates those files as well.

ah - definitely not. let me undo that.

**Comment by rahulku** [comment]
@zhassan-aws @celinval - is the FF on the s2n-quic an issue?

**Comment by tautschnig** [comment]
> @zhassan-aws @celinval - is the FF on the s2n-quic an issue?

The commit takes us back in time on s2n-quic from August 22nd to June 15th.

**Comment by celinval** [comment]
> > @zhassan-aws @celinval - is the FF on the s2n-quic an issue?
> 
> The commit takes us back in time on s2n-quic from August 22nd to June 15th.

For future reference, @rahulku probably forgot to run `git submodule update` after pulling the latest main. This indeed would be an issue.

**Pull request closed without merging**
