### PR TITLE
Auto-upload macOS ARM binaries to draft release

### PR DESCRIPTION
**Pull request by tautschnig**
In #3266 a job to build macOS ARM binaries was added, but the artifacts weren't yet propagated to the release. This PR adds this missing step.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — COMMENTED** [review]
Great catch, thank you. Is there any way of testing that this works?

**Comment by tautschnig** [comment]
Looks we are also caught by https://github.com/actions/checkout/issues/1809

**Comment by tautschnig** [comment]
> Great catch, thank you. Is there any way of testing that this works?

Not an easy one that I know of, I'm afraid.

**Comment by adpaco-aws** [comment]
It's not easy to test but also not the end the of the world if it fails for any reason. In that case, one only needs to go the Release Bundle summary (e.g., [this one](https://github.com/model-checking/kani/actions/runs/9780933430) for version 0.53.0), then download and attach the missing bundles to the release.

**Comment by celinval** [comment]
Wait, is there a reason why we are not running any test in the image like we do with the other images?

**Comment by tautschnig** [comment]
> Wait, is there a reason why we are not running any test in the image like we do with the other images?

We could certainly add such tests, but that wouldn't in itself test that the release auto-upload works.

**Comment by celinval** [comment]
No, but it would test the image which I think is more important.

**Review by adpaco-aws — APPROVED** [review]

**Comment by adpaco-aws** [comment]
Thanks @tautschnig for adding this! 😃 

> Wait, is there a reason why we are not running any test in the image like we do with the other images?

@celinval I've opened https://github.com/model-checking/kani/issues/3331 to keep track of that work. Please feel free to comment if I missed something.

**Pull request merged**
