### PR TITLE
Add range demo example

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

Add an example that can be used to demo Kani.

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — APPROVED** [review]
We should probably add the rectangle example as well somewhere for demonstrations, it has come in handy for demoing the extension.

**Comment by zhassan-aws** [comment]
It's available under https://github.com/model-checking/kani/tree/main/tests/cargo-kani/rectangle-example

**Comment by jaisnan** [comment]
> It's available under https://github.com/model-checking/kani/tree/main/tests/cargo-kani/rectangle-example

I forgot completely. Thanks for reminding! And for this example.

**Review by adpaco-aws — APPROVED** [review]
Thanks @zhassan-aws !

**Pull request merged**
