### PR TITLE
Change 'cargo kani --visualize' to 'kani --visualize ...'

### PR DESCRIPTION
**Pull request by CarlKCarlK**
was: cargo kani --visualize
now: kani test.rs --visualize --enable-unstable

### Description of changes: 

I needed to change the example to make it work.

### Resolved issues:

Resolves #ISSUE-NUMBER

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
Hi @CarlKCarlK. Thanks for the pull request!

The command in the documentation is actually correct since the [example referred to](https://github.com/model-checking/kani/tree/main/docs/src/tutorial/first-steps-v1/) is a cargo package, so it needs to be run with `cargo kani`. This is consistent with the command used right before that section: https://model-checking.github.io/kani/tutorial-first-steps.html#getting-a-trace

**Comment by celinval** [comment]
> Hi @CarlKCarlK. Thanks for the pull request!
> 
> The command in the documentation is actually correct since the [example referred to](https://github.com/model-checking/kani/tree/main/docs/src/tutorial/first-steps-v1/) is a cargo package, so it needs to be run with `cargo kani`. This is consistent with the command used right before that section: https://model-checking.github.io/kani/tutorial-first-steps.html#getting-a-trace

Just to clarify, both commands work since this crate doesn't have any dependency. We use `cargo` in our tutorials since we expect most users to use Kani via Cargo. Cheers!

**Comment by CarlKCarlK** [comment]
Got it. Thanks.

**Comment by zhassan-aws** [comment]
Closing PR based on discussion above.

**Pull request closed without merging**
