### PR TITLE
Upgrade Rust toolchain to `nightly-2024-03-01`

### PR DESCRIPTION
**Pull request by adpaco-aws**
Upgrades the Rust toolchain to `nightly-2024-03-01`. The Rust compiler PRs that triggered changes in this upgrades are:
 * https://github.com/rust-lang/rust/pull/121516
 * https://github.com/rust-lang/rust/pull/121598
 * https://github.com/rust-lang/rust/pull/121489
 * https://github.com/rust-lang/rust/pull/121783

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]
Thanks Adrian!

**Comment by celinval** [comment]
Please just make sure there's no significant performance degradation before merging.

**Comment by adpaco-aws** [comment]
Unfortunately I'm getting consistent >400% regressions in `solver_runtime` for `s2n-quic/quic/s2n-quic-core/recovery::rtt_estimator::test::weighted_average_test` (see [this CI run](https://github.com/model-checking/kani/actions/runs/8115665074) for example). Other values like program steps, VCCs, etc. haven't really changed.

**Comment by celinval** [comment]
can you manually run before and after the PR to see if that's the case?

**Comment by zhassan-aws** [comment]
This test is known to have high variance in performance, e.g. see https://github.com/model-checking/kani/actions/runs/7453782015

The numbers in this PR are on par with the numbers in previous PRs, so I would consider this to be noise. You can confirm by running the test locally a number of times with and without the changes.

**Review by feliperodri — APPROVED** [review]

**Comment by adpaco-aws** [comment]
Thanks all for your feedback. I've run each version 10 times and the results are:
| iter. | before | after |
| ---   | ---    | ---   |
| 1 | 150.85266 | 200.95573 |
| 2 | 150.59746 | 200.90263 |
| 3 | 150.4481 | 202.78355 |
| 4 | 150.52237 | 201.8042 |
| 5 | 150.50912 | 200.75551 |
| 6 | 150.19904 | 200.7821 |
| 7 | 151.47997 | 200.9002 |
| 8 | 150.85907 | 200.75055 |
| 9 | 150.36966 | 204.47491 |
| 10 | 150.9473 | 201.89137 |

So it looks like there's a performance regression of about +50s/+33% for this test.

**Comment by adpaco-aws** [comment]
After some discussion, we consider that **the regression is due to SAT variability**.

No data suggests that the problem is more difficult per se after the toolchain upgrade. For example, runtime symex remains constant in all cases (~0.8s), as does program size (16292 steps) and VCCs (615/231).

The table below shows SAT-solving time for the UNSATISFIABLE instance in each of the iterations.

| iter. | before | after |
| --- | --- | --- |
| 1 | 146.51s | 196.37s |
| 2 | 146.25s | 196.281s |
| 3 | 146.032s | 198.212s |
| 4 | 146.176s | 197.226s |
| 5 | 146.168s | 196.173s |
| 6 | 145.878s | 196.158s |
| 7 | 147.131s | 196.314s |
| 8 | 146.485s | 196.165s |
| 9 | 146.028s | 199.885s |
| 10 | 146.612s | 197.307s |

If we compare this with the table posted in my previous comment, we can conclude that the total time increase is due to the increase in SAT-solving for the UNSATISFIABLE instance. Therefore, there is no reason to block this toolchain upgrade.

@zhassan-aws pointed out that there's almost no difference before/after this toolchain upgrade if we use CaDiCaL instead (the current solver is Kissat). So we'll propose switching the solver to CaDiCaL for this test.

**Pull request merged**
