### PR TITLE
Update the rust toolchain to nightly-2024-04-03

### PR DESCRIPTION
**Pull request by tautschnig**
Changes required due to:
- rust-lang/rust@3da115a93b Add Ord::cmp for primitives as a BinOp in MIR

Resolves: #3130 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by tautschnig** [comment]
The changes in this PR make Kani build with the 2024-04-03 toolchain, but compiletest then fails as we run into https://github.com/rust-lang/rust/blob/d009f60b55fe4527e7ddf122bc4520f351d7b9d4/compiler/stable_mir/src/mir/body.rs#L373 (i.e., an `unimplemented!` in stable_mir that was added as part of the PR that required those changes on our side in the first place). @celinval might be best placed to help resolve this?

**Comment by celinval** [comment]
Damn... this isn't good. This PR shouldn've been approved. This Fix definitely needs to be addressed on the rustc side.

**Comment by celinval** [comment]
BTW, the fix to StableMIR has been approved: https://github.com/rust-lang/rust/pull/123655

**Comment by tautschnig** [comment]
> BTW, the fix to StableMIR has been approved: [rust-lang/rust#123655](https://github.com/rust-lang/rust/pull/123655)

Thank you @celinval for implementing this fix upstream! As this is now also merged we should be able to bump the toolchain tomorrow morning.

**Comment by tautschnig** [comment]
Closing in favour of #3144.

**Pull request closed without merging**
