### PR TITLE
Single-commit gh-pages

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

1. Bump version on our gh-pages publishing actions.
2. Use `single-commit` to have it nuke history.

Why? We haven't looked at this history basically ever. This reduces repository/clone size further. I'm proposing we just let it nuke history.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]
I'm assuming we can easily generate older versions of the doc by running the build docs script in an older commit (if we ever have to).

**Comment by tedinski** [comment]
That should be the case.

**Review by adpaco-aws — APPROVED** [review]
This will remove past `bookrunner` results as well. In my opinion, this is not a big issue because we should be getting these stats some other way, but just wanted to note that here.

**Comment by tedinski** [comment]
> This will remove past bookrunner results as well.

Good call, I didn't think of that. I'm still inclined to merge as well. Maybe I'll wait for one more approval though in light of this wrinkle?

**Comment by adpaco-aws** [comment]
I think it's the same as with `gh-pages` history, we can reproduce the results if we need to.

**Review by zhassan-aws — APPROVED** [review]

**Comment by tedinski** [comment]
Hmm

```
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: Cannot force-push to this protected branch        
To https://github.com/model-checking/kani.git
 ! [remote rejected] github-pages-deploy-action/8cv2aejr6 -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/model-checking/kani.git'
```

I thought we had branch protections disabled for `gh-pages`.

**Pull request merged**
