### PR TITLE
Delay printing playback harness until after verification status

### LINKED ISSUE #2462: Concrete playback warnings / results printed in the middle of the verification report
I tried this code:
```rust
    #[kani::proof]
    fn dummy() {
        kani::cover!(kani::any::<u32>() != 10);
    }
```

using the following command line invocation:

```
kani --concrete-playback=print --harness dummy file.rs -Z concrete-playback
```

with Kani version:

I expected to see this happen: The concrete test case is printed after the verification report

Instead, this happened: The test case is printed in between CBMC solver information and the verification result:

<details>

```
Checking harness verify::dummy...
CBMC 5.83.0 (cbmc-5.83.0)
CBMC version 5.83.0 (cbmc-5.83.0) 64-bit x86_64 linux
Reading GOTO program from file /tmp/original__RNvNtCsjSo4igdeNiX_8original6verify5dummy.for-verify-dummy.out
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 16 object bits, 48 offset bits (user-specified)
Starting Bounded Model Checking
Runtime Symex: 0.00290956s
size of program expression: 255 steps
simple slicing removed 3 assignments
Generated 2 VCC(s), 2 remaining after simplification
Runtime Postprocess Equation: 3.5862e-05s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000394059s
Running propositional reduction
Post-processing
Runtime Post-process: 3.677e-06s
Solving with MiniSAT 2.2.1 with simplifier
829 variables, 35 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.000117994s
Runtime decision procedure: 0.000565902s
Concrete playback unit test for `verify::dummy`:
\```
#[test]
fn kani_concrete_playback_dummy_6616739614161460699() {
    let concrete_vals: Vec<Vec<u8>> = vec![
        // 32778
        vec![10, 128, 0, 0],
    ];
    kani::concrete_playback_run(concrete_vals, dummy);
}
\```
INFO: To automatically add the concrete playback unit test `kani_concrete_playback_dummy_6616739614161460699` to the src code, run Kani with `--concrete-playback=inplace`.

RESULTS:
Check 1: verify::dummy.cover.1
         - Status: SATISFIED
         - Description: "cover condition: kani::any::<u32>() != 10"
         - Location: original.rs:30:9 in function verify::dummy


SUMMARY:
 ** 0 of 0 failed

 ** 1 of 1 cover properties satisfied


VERIFICATION:- SUCCESSFUL
Verification Time: 0.02666074s
```
</details>

### PR DESCRIPTION
**Pull request by YoshikiTakashima**
### Description of changes: 

Delay printing of harness until the verification status message is printed.

### Resolved issues:

Resolves #2462

### Call-outs:

Again, not familiar with testing this feature, so feel free to suggest any improvements on that front.

### Testing:

* How is this change tested? `tests/ui/concrete-playback/message-order`

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — COMMENTED** [review]
Have you tried running concrete playback with --inplace. Does the behavior of pasting the unit test into the source get impacted by this change? Even if it's not, I think it would be good to have a few regression tests with inplace just so we know the impact.

**Comment by YoshikiTakashima** [comment]
Good pt. I don't think so, but let me write another test to be sure.

**Review by celinval — CHANGES_REQUESTED** [review]
May I suggest a different approach? Can you move the call to `gen_and_add_concrete_playback()` to `harness_runner` module instead of `call_cbmc`. We need to make sure that call is made after the result was rendered.

**Comment by YoshikiTakashima** [comment]
@celinval I can do that. The inputs to `gen_and_add_concrete_playback()` will need to move into the `VerificationResults` to be available but that might be cleaner.

**Comment by YoshikiTakashima** [comment]
@celinval thanks for the suggestion. This was way easier, no change to `VerificationResult` required.

**Comment by YoshikiTakashima** [comment]
Should be good to go. 

@jaisnan The similar tests to what you requested seem to have merged as part of #2464 and #2477

**Review by celinval — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
