### PR TITLE
Negative test case for `variant_count`

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Adds a negative test for the `variant_count` intrinsic. Can easily converted into a positive one when support is added.

### Resolved issues:

Part of #727 

### Testing:

* How is this change tested? Adding another test.

* Is this a refactor change? N/A

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by tedinski — APPROVED** [review]

**Comment by celinval** [comment]
Should we check what kind of error is given to the user?

**Comment by adpaco-aws** [comment]
> Should we check what kind of error is given to the user?

The test is intentionally written this way to avoid error checking and to enable a smooth transition into a positive test. This is a good candidate for the newer testing suite we were discussing, and I want to move all these negative tests into that suite once it is available. But we can move it to `expected` for now if this is a concern, I am just afraid I will lose track of them in there.

**Comment by celinval** [comment]
Can you add the version without comments as a fixme test?

**Comment by adpaco-aws** [comment]
@celinval just added the "fixme" test as requested and updated the negative one (removed commented out code to make it simpler).

**Review by celinval — APPROVED** [review]
Thanks!

**Pull request merged**
