### PR TITLE
Upgrade rust toolchain to 2023-04-30

### LINKED ISSUE #2451: Update rust toolchain version to nightly-2023-04-30

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

Push rust toolchain by one day to 2023-04-30.

### Resolved issues:

Resolves #2451 

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested? Current regressions

* Is this a refactor change? No

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
This is blocked by https://github.com/model-checking/kani/issues/2457.

**Comment by tautschnig** [comment]
See https://github.com/model-checking/kani/issues/2457#issuecomment-1568212954 for the link to the solution on the CBMC side. We might have to hold back on this upgrade until after the next CBMC release (due 2023-06-08).

**Comment by tautschnig** [comment]
CBMC 5.85.0 has been released. A CBMC version bump PR should make this upgrade feasible.

**Review by celinval — APPROVED** [review]
We really need to refactor this test... sorry

**Review by qinheping — APPROVED** [review]

**Pull request merged**
