### PR TITLE
Partial support for `bitreverse`

### LINKED ISSUE #745: Unimplemented intrinsic: `bitreverse`
`bitreverse` is not supported at the moment.

It appears CBMC does not have available the `bitreverse` builtin according to [the irep IDs definitions](https://github.com/diffblue/cbmc/blob/develop/src/util/irep_ids.def). I will talk to CBMC folks to see what can be done about this, but another approach here is to implement the logic for bit reversal it in RMC.

### PR DESCRIPTION
**Pull request by adpaco-aws**
### Description of changes: 

Adds partial support for the `bitreverse` intrinsic.

It is supposed to work until support is added in CBMC, but created #778 for tracking and doing the remaining work then.

### Resolved issues:

Resolves #745 
Opens #778 

### Testing:

* How is this change tested? Regression + new "fixme" test.

* Is this a refactor change? No.

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — CHANGES_REQUESTED** [review]
Can you please describe what partial support means here? From the user perspective, what has changed with this PR?

**Comment by adpaco-aws** [comment]
> Can you please describe what partial support means here? From the user perspective, what has changed with this PR?

Right, it would be best to claim support in the work for #778 and leave the current support value as it was. What do you think?

**Comment by adpaco-aws** [comment]
Dropped the change on the table and sync'd with `main`.

**Review by celinval — APPROVED** [review]
Thanks

**Pull request merged**
