### PR TITLE
Bump CBMC version to 5.88.0

### PR DESCRIPTION
**Pull request by qinheping**
### Description of changes: 

Upgrade to latest CBMC version.

### Resolved issues:

Resolves #ISSUE-NUMBER

### Related RFC:

Optional #ISSUE-NUMBER.

### Testing:

* How is this change tested?

* Is this a refactor change?

### Checklist
- [ ] Each commit message has a non-empty body, explaining why the change was made
- [ ] Methods or procedures are documented
- [ ] Regression or unit tests are included, or existing tests cover the modified code
- [ ] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — APPROVED** [review]
Thanks!

**Comment by zhassan-aws** [comment]
Please update the version on the following line as well:

https://github.com/model-checking/kani/blob/main/scripts/kani-regression.sh#L22C22-L22C22

**Review by feliperodri — APPROVED** [review]
🚢

**Review by zhassan-aws — APPROVED** [review]

**Comment by zhassan-aws** [comment]
Just realized that we should've labeled this PR with Z-BenchCI so that benchcomp is run :(

**Comment by qinheping** [comment]
> Just realized that we should've labeled this PR with Z-BenchCI so that benchcomp is run :(

Yes. However, it seems that the benchcomp is running for this PR https://github.com/model-checking/kani/actions/runs/5627831808/job/15250966176. Let's wait for the result to see if we want to revert this PR.

**Pull request merged**
