### PR TITLE
Fix verify-std-check outcome check

### PR DESCRIPTION
**Pull request by celinval**
It looks like I used `output` instead of `outcome` variable.

I noticed that [this PR](https://github.com/model-checking/kani/pull/3392) should've failed the workflow but it didn't because of this mistake.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — APPROVED** [review]
Oops, should have caught this in my review. in any case, thanks!  

Can we add a comment somewhere that all toolchain upgrade failures that are resolved manually should trigger a failure for this CI check?

**Comment by celinval** [comment]
We currently have the following blob at the top of the workflow file:
```yml
# We expect toolchain updates to potentially break this workflow in cases where
# the version tracked in the `verify-rust-std` is not compatible with newer
# versions of the Rust toolchain.
#
# Changes unrelated to the toolchain should match the current status of main.
```
Do you have anything else in mind?

**Comment by jaisnan** [comment]
> We currently have the following blob at the top of the workflow file:
> 
> ```yaml
> # We expect toolchain updates to potentially break this workflow in cases where
> # the version tracked in the `verify-rust-std` is not compatible with newer
> # versions of the Rust toolchain.
> #
> # Changes unrelated to the toolchain should match the current status of main.
> ```
> 
> Do you have anything else in mind?

Just maybe a small clarification like ->

```
# We expect toolchain updates to potentially break this workflow in cases where
# the version tracked in the `verify-rust-std` is not compatible with newer 
# versions of the Rust toolchain. 
# For example, toolchain upgrade breaks such as 
# https://github.com/model-checking/kani/issues/3369.
#
# Changes unrelated to the toolchain should match the current status of main.
```

It's okay if this change is not added, this is purely for me because i like examples in comments.

**Comment by celinval** [comment]
I agree that an example can be very helpful, but I'm not sure the PR you mentioned is a good reference. Maybe we can add a better link later.

The PR didn't actually fail the workflow, and the workflow logs themselves won't be available for more than a few days. So it might be confusing to use this as a reference.

**Pull request merged**
