### PR TITLE
Automatic toolchain upgrade improvements

### PR DESCRIPTION
**Pull request by tautschnig**
### Description of changes: 

1. Build and run regression tests.
2. File an issue instead of creating a PR when either of the checks fail.

### Resolved issues:

N/a

### Related RFC:

n/a

### Call-outs:

Tested in my fork, which doesn’t support issues, so it’s still to be tested in full over here.

### Testing:

* How is this change tested? Ran in my fork.

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- n/a Methods or procedures are documented
- n/a Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
Will the PR still get created if the build or regressions fail?

**Comment by celinval** [comment]
> Will the PR still get created if the build or regressions fail?

It doesn't look like it:

```yml
  if: ${{ env.next_step == 'create_pr' }}
```

**Review by celinval — APPROVED** [review]
Thanks

**Comment by zhassan-aws** [comment]
> It doesn't look like it

In that case, would that result in the bot creating the same issue multiple times (every time the cronjob runs)?

**Comment by celinval** [comment]
> > It doesn't look like it
> 
> In that case, would that result in the bot creating the same issue multiple times (every time the cronjob runs)?

That's a good point

**Comment by tautschnig** [comment]
> > > It doesn't look like it
> > 
> > 
> > In that case, would that result in the bot creating the same issue multiple times (every time the cronjob runs)?
> 
> That's a good point

Reading the action's source code: I think that could happen. May I postpone addressing this limitation when we bump into it?

**Comment by tautschnig** [comment]
> > > > It doesn't look like it
> > > 
> > > 
> > > In that case, would that result in the bot creating the same issue multiple times (every time the cronjob runs)?
> > 
> > 
> > That's a good point
> 
> Reading the action's source code: I think that could happen. May I postpone addressing this limitation when we bump into it?

Nevermind, I now added code so as not to create issues when one already exists.

**Pull request merged**
