### PR TITLE
README.md & getting-started.md

### PR DESCRIPTION
**Pull request by Rustmilian**
### Description of changes: 
Fact corrected & linked to source. 
Read : [The Rust Programming Language Book, Chapter 19.1; "Unsafe Superpowers"](https://doc.rust-lang.org/stable/book/ch19-01-unsafe-rust.html#unsafe-superpowers) to see why the original is incorrect.
Also added a separator for better readability.

This change is necessary for correctness & additionally dispelling a common misconceptions.

___
### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.
___

### CODE REVIEW

**Comment by adpaco-aws** [comment]
Hi @Rustmilian , thanks for the PR!

The change looks good to me. Would you mind applying it in [the "Getting started" section of the documentation](https://model-checking.github.io/kani/#getting-started) as well?

**Comment by Rustmilian** [comment]
@adpaco-aws Sure thing.

**Review by adpaco-aws — APPROVED** [review]
Looks great. Thank you, @Rustmilian !

**Comment by Rustmilian** [comment]
Woop Woop. 🙌

**Pull request merged**
