### PR TITLE
Allow `&bool` in asserts

### LINKED ISSUE #2108: Kani assert override is more restrictive than standard assert
This code works as a test but fails with Kani:

```rust
#[cfg_attr(test, test)]
#[cfg_attr(kani, kani::proof)]
fn check() {
    let v: bool = true;
    assert!(&v);
}
```

With test: builds successfully, no warnings/errors, test passes.

With kani:

```text
error[E0308]: mismatched types
  --> test_bool_ref.rs:7:13
   |
7  |     assert!(&v);
   |     --------^^-
   |     |       |
   |     |       expected `bool`, found `&bool`
   |     arguments to this function are incorrect
   |
note: function defined here
  --> /home/ubuntu/rmc/library/kani/src/lib.rs:62:14
   |
62 | pub const fn assert(_cond: bool, _msg: &'static str) {
   |              ^^^^^^
```

### PR DESCRIPTION
**Pull request by zhassan-aws**
### Description of changes: 

From investigating #2108, it turns out that due to how the standard library expands `assert!(x)` as
```rust
    if !x {
        ::core::panicking::panic("assertion failed: x")
    };
```
the following is valid Rust code:
```rust
fn main() {
    let b: bool = true;
    assert!(&b);
}
```
because it gets expanded to:
```rust
fn main() {
    let b: bool = true;
    if !&b {
        ::core::panicking::panic("assertion failed: &b")
    }
}
```
which, however, is rejected by Kani because `&b` is not a boolean (only `!&b` is!).

This PR adds a hacky fix, which is to inject `!!` (i.e. double negation) before the condition.

### Resolved issues:

Resolves #2108 

### Related RFC:

Optional #ISSUE-NUMBER.

### Call-outs:

TBH, I'm not sure about whether this should be merged as it is quite hacky. We should look into where this occurs, and why it is valid.

### Testing:

* How is this change tested? Added a new test

* Is this a refactor change? No

### Checklist
- [X] Each commit message has a non-empty body, explaining why the change was made
- [X] Methods or procedures are documented
- [X] Regression or unit tests are included, or existing tests cover the modified code
- [X] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — COMMENTED** [review]
Did you try defining `kani::assert()` using `AsRef<bool>` instead?

**Comment by celinval** [comment]
> Did you try defining `kani::assert()` using `AsRef<bool>` instead?

Actually, I don't think that will work. :(

**Review by celinval — APPROVED** [review]

**Comment by tedinski** [comment]
Seems fine, can we change the PR name to something slightly more customer-facing in advance of merging? "Accept `&bool` in asserts, like Rust's assert macro does" perhaps

**Comment by zhassan-aws** [comment]
> can we change the PR name to something slightly more customer-facing in advance of merging?

Done.

**Pull request merged**
