### PR TITLE
Remove --visualize and cbmc-viewer call

### PR DESCRIPTION
**Pull request by jaisnan**
Current status:
1. Removing CBMC-Viewer invocation from kani
2. Remove `--visualize` flag

Todo:
1. Remove python from CI jobs
3. Update documentation

Resolves #

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — COMMENTED** [review]
Don't forget to remove Python from the setup flow

**Comment by zhassan-aws** [comment]
@jaisnan Is this PR blocked on anything?

**Comment by celinval** [comment]
I think we decided to deprecate it first, but it should be ready to go. @jaisnan can you please resolve the conflicts so we can merge this?

**Comment by zhassan-aws** [comment]
The changes from this PR were included in #3699 which was merged. Closing this one.

**Pull request closed without merging**
