### PR TITLE
Fix visibility of some Kani intrinsics

### PR DESCRIPTION
**Pull request by artemagvanian**
This PR fixes inadvertently exposing some of the unstable Kani intrinsics.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by jaisnan — COMMENTED** [review]
Can you change the equivalent methods in `kani_core` as well? Is that necessary?

**Comment by artemagvanian** [comment]
> Can you change the equivalent methods in `kani_core` as well? Is that necessary?

Yes, it is -- thanks for catching this

**Comment by artemagvanian** [comment]
It seems like the shadow memory tests depend on the shadow memory functions to be public -- I wonder if this is desired

**Comment by celinval** [comment]
For now, I would just add the unstable tag and `#[doc(hidden)]` to them so we don't have to change the tests.

**Review by celinval — APPROVED** [review]
Thanks!

**Pull request merged**
