### PR TITLE
Emit an error when proof_for_contract function is not found

### PR DESCRIPTION
**Pull request by zhassan-aws**
Currently, Kani panics if the function specified in the `proof_for_contract` attribute is not found (e.g. because the function is not reachable) (see #3467). This PR adds an error message pointing out the issue.

Towards #3467 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]
I wonder if this should be done as part of `kani::middle::check_reachable_items` which is where we run our validations. The main advantage is that we emit all possible configuration errors.

I won't block this PR though since it's a clear improvement to the existing flow. Thanks!

**Comment by zhassan-aws** [comment]
> I wonder if this should be done as part of `kani::middle::check_reachable_items` which is where we run our validations

That makes sense. I'll check if it's easy to do that.

**Comment by zhassan-aws** [comment]
I moved the check to `check_reachable_items`.

**Review by celinval — APPROVED** [review]
Thanks!!!

**Pull request merged**
