### PR TITLE
Treat lack of proof harnesses as success

### LINKED ISSUE #1857: Allow kani to return EXIT_SUCCESS for empty proof harnesses
**Feature:** Treat empty harnesses as successes rather than failures, either by default or through a flag. This is helpful to make generic CI checkers that automatically pick up proofs when they exist for a project and ignore them when they don't. As an example, consider that `cargo test` does not fail on an empty harness.

**Current behaviour:** `kani` unconditionally errors out if there's no proof harness.

```
alexgv@mypc:~$ cargo new mwe
     Created binary (application) `mwe` package
alexgv@mypc:~$ cd mwe && cargo kani || echo NONZERO_EXIT
   Compiling mwe v0.1.0 (/home/alexgv/mwe)
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Error: No proof harnesses (functions with #[kani::proof]) were found to verify.
NONZERO_EXIT
```

### PR DESCRIPTION
**Pull request by tedinski**
### Description of changes: 

Do not error out on lack of proof harnesses.

### Resolved issues:

* Resolves #1857

### Call-outs:

Our output is now consistent with `cargo test` on 0 harnesses: give the same summary information, but no tests/proofs were found. I think we could do better, but maybe now's not the time.

### Testing:

* How is this change tested? ci

* Is this a refactor change? no

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by zhassan-aws — COMMENTED** [review]
Thanks! Can we add a test?

**Review by celinval — COMMENTED** [review]
Thank you for doing this. Can we still add a message though to say that no proof harness was found?

**Comment by tedinski** [comment]
It seemed wasteful to write one test for this, much less the two tests needed to both check expected output and return value, but I guess I'm out voted

**Comment by celinval** [comment]
Yeah, two tests do feel a bit overwhelming. Too bad this can't be done in one single test.

**Comment by tedinski** [comment]
Compromise? I made this slightly more refactor-like by just moving the existing code to a new place as `println` instead of `bail`. And added the minimal test for exist status.

**Review by celinval — COMMENTED** [review]
Can you please make sure this test actually runs? I remember having problems with `cargo kani` tests that don't have an `expected` file.

**Comment by tedinski** [comment]
Oh yeah, definitely not working. Well this is disconcerting, there's actually NO way to write a test to ensure `cargo kani` succeeds.

**Comment by zhassan-aws** [comment]
I think adding an `expected` file, even if empty, would guarantee that `cargo kani` runs.

**Comment by tedinski** [comment]
It runs, but nothing pays attentions to the exit status

**Review by celinval — APPROVED** [review]

**Review by zhassan-aws — APPROVED** [review]

**Pull request merged**
