### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by karkhaz**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — APPROVED** [review]

**Comment by karkhaz** [comment]
On [this run](https://github.com/model-checking/kani/actions/runs/5272434464?pr=2528) there was a 58% increase in solver runtime (59s -> 93s) for s2n-quic/quic/s2n-quic-core/slice::tests::vectored_copy_fuzz_test

**Comment by zhassan-aws** [comment]
> On [this run](https://github.com/model-checking/kani/actions/runs/5272434464?pr=2528) there was a 58% increase in solver runtime (59s -> 93s) for s2n-quic/quic/s2n-quic-core/slice::tests::vectored_copy_fuzz_test, will re-run just in case

This always happens mysteriously with version bumps!

**Comment by zhassan-aws** [comment]
Or rather, with many PRs. See for example this PR that adds an RFC :)

https://github.com/model-checking/kani/actions/runs/5272168064

**Comment by adpaco-aws** [comment]
> Or rather, with many PRs. See for example this PR that adds an RFC :)
> 
> https://github.com/model-checking/kani/actions/runs/5272168064

Yeah, getting a couple CI failures in that PR was surprising to me. I guess the SAT procedure for benchmark is unstable? I wonder if we should start documenting the issue and keeping a list of unstable benchmarks.

**Comment by celinval** [comment]
> > Or rather, with many PRs. See for example this PR that adds an RFC :)
> > https://github.com/model-checking/kani/actions/runs/5272168064
> 
> Yeah, getting a couple CI failures in that PR was surprising to me. I guess the SAT procedure for benchmark is unstable? I wonder if we should start documenting the issue and keeping a list of unstable benchmarks.

Not surprised at all. We've been seeing this instability issue since we added this regression even for changes to the documentation.

I think adding the list of unstable tests will help, but we really need to investigate a bit more. Is Kani performance that unstable (which would be a poor experience for our users) or is this an infrastructure issue?

**Pull request merged**
