### PR TITLE
Upgrade to CBMC 6.2.0

### PR DESCRIPTION
**Pull request by zhassan-aws**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
This is blocked by https://github.com/Homebrew/homebrew-core/pull/183287. Turning it into a draft till it's resolved.

**Comment by qinheping** [comment]
Resolves: #3507

**Comment by tautschnig** [comment]
We'll have an updated CBMC release the next days at which point we'll be able to resolve this.

**Comment by tautschnig** [comment]
Closing as we'll upgrade to 6.3.1.

**Pull request closed without merging**
