### PR TITLE
Added ability to figure out workspaces from cargo kani.

### LINKED ISSUE #1420: Better Behavior for `cargo kani`: workspaces and `--manifest-path`
Requested feature: `cargo kani` should have `cargo test` like semantics. Workspaces should be supported,

Use case: More intuitive behavior for Cargo Kani. Also helps with building dependencies to hard-code linking

Link to relevant documentation (Rust reference, Nomicon, RFC): "https://doc.rust-lang.org/cargo/commands/cargo-test.html"

Test case:

```bash
git clone https://github.com/YoshikiTakashima/kani.git
cd kani
git checkout yoshi-proptest-primitive
git checkout eac76a7e -- library/proptest
cargo clean; cargo build --workspace

# workspaces
cd library/proptest
cargo kani --only-codegen
ls # shows library/proptest/target, not in the right workspace

# --manifest-path
cp Cargo.toml Cargo.test.toml
cargo kani --only-codegen --manifest-path=Cargo.test.toml
```

### PR DESCRIPTION
**Pull request by YoshikiTakashima**
### Description of changes:  

Made cargo-kani deal with work-spaces when finding `target`. This avoids `target` getting plopped down in middle of work-spaces when they should not be. Also helps if the library needs to link symtabs from neighboring work-spaces.

### Resolved issues: 

Resolves #1420 

### Call-outs:

The feature relies on parsing json from `cargo metadata`.

### Testing:

* How is this change tested? Make a project with workspaces and run tests on it.

* Is this a refactor change? No

### Checklist
- [x] Each commit message has a non-empty body, explaining why the change was made
- [x] Methods or procedures are documented
- [x] Regression or unit tests are included, or existing tests cover the modified code
- [x] My PR is restricted to a single feature or bugfix

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Review by celinval — COMMENTED** [review]
Should we use the cargo metadata crate instead? https://crates.io/crates/cargo_metadata

**Comment by YoshikiTakashima** [comment]
@celinval I implemented the request.

**Comment by tedinski** [comment]
See `tests/cargo-kani/ws-crate-type-bin/` for a test with a workspace

**Review by celinval — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
